# Generated by Django 4.2.6 on 2023-10-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_customuser_is_profile_created_workerdetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
