# Generated by Django 4.2.6 on 2023-10-16 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_workerdetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdetails',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.locations'),
        ),
    ]
