# Generated by Django 4.2.6 on 2023-10-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_remove_services_locations_servicelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
