# Generated by Django 4.2.6 on 2023-10-31 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_locations_latitude_locations_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdetails',
            name='join_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_address', models.TextField()),
                ('issue', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentification.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workerdetails',
            name='bookings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentification.bookings'),
        ),
    ]
