# Generated by Django 4.2.6 on 2023-10-31 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_alter_workerdetails_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerdetails',
            name='bookings',
        ),
        migrations.CreateModel(
            name='WorkerBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.bookings')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
