# Generated by Django 4.2.6 on 2023-11-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0010_remove_workerdetails_bookings_workerbookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='service',
        ),
        migrations.AddField(
            model_name='bookings',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
