# Generated by Django 4.2.6 on 2023-11-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_remove_bookings_service_bookings_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
