# Generated by Django 4.2.6 on 2023-11-15 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_review_workerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_recieved', models.BooleanField(default=False)),
                ('is_payed', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('Bookings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.workerbookings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_user', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
