# Generated by Django 4.2.6 on 2023-11-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0015_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date_time',
            new_name='payed_date_time',
        ),
        migrations.AddField(
            model_name='payment',
            name='received_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
