# Generated by Django 4.2.6 on 2023-11-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0017_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Bookings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.bookings'),
        ),
    ]
