# Generated by Django 4.2.6 on 2023-11-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0020_adminwallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminwallet',
            name='admin',
        ),
        migrations.AddField(
            model_name='adminwallet',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
